// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitMsg struct {
	RfbHeader            string       `protobuf:"bytes,1,opt,name=RfbHeader,json=rfbHeader,proto3" json:"RfbHeader,omitempty"`
	RfbVersion           string       `protobuf:"bytes,2,opt,name=RfbVersion,json=rfbVersion,proto3" json:"RfbVersion,omitempty"`
	FBHeight             uint32       `protobuf:"varint,3,opt,name=FBHeight,json=fBHeight,proto3" json:"FBHeight,omitempty"`
	FBWidth              uint32       `protobuf:"varint,4,opt,name=FBWidth,json=fBWidth,proto3" json:"FBWidth,omitempty"`
	SecType              uint32       `protobuf:"varint,5,opt,name=SecType,json=secType,proto3" json:"SecType,omitempty"`
	StartTime            uint32       `protobuf:"varint,6,opt,name=StartTime,json=startTime,proto3" json:"StartTime,omitempty"`
	DesktopName          string       `protobuf:"bytes,7,opt,name=DesktopName,json=desktopName,proto3" json:"DesktopName,omitempty"`
	PixelFormat          *PixelFormat `protobuf:"bytes,8,opt,name=PixelFormat,json=pixelFormat,proto3" json:"PixelFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InitMsg) Reset()         { *m = InitMsg{} }
func (m *InitMsg) String() string { return proto.CompactTextString(m) }
func (*InitMsg) ProtoMessage()    {}
func (*InitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *InitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMsg.Unmarshal(m, b)
}
func (m *InitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMsg.Marshal(b, m, deterministic)
}
func (m *InitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMsg.Merge(m, src)
}
func (m *InitMsg) XXX_Size() int {
	return xxx_messageInfo_InitMsg.Size(m)
}
func (m *InitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InitMsg proto.InternalMessageInfo

func (m *InitMsg) GetRfbHeader() string {
	if m != nil {
		return m.RfbHeader
	}
	return ""
}

func (m *InitMsg) GetRfbVersion() string {
	if m != nil {
		return m.RfbVersion
	}
	return ""
}

func (m *InitMsg) GetFBHeight() uint32 {
	if m != nil {
		return m.FBHeight
	}
	return 0
}

func (m *InitMsg) GetFBWidth() uint32 {
	if m != nil {
		return m.FBWidth
	}
	return 0
}

func (m *InitMsg) GetSecType() uint32 {
	if m != nil {
		return m.SecType
	}
	return 0
}

func (m *InitMsg) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *InitMsg) GetDesktopName() string {
	if m != nil {
		return m.DesktopName
	}
	return ""
}

func (m *InitMsg) GetPixelFormat() *PixelFormat {
	if m != nil {
		return m.PixelFormat
	}
	return nil
}

type PointerEvent struct {
	Mask                 uint32   `protobuf:"varint,1,opt,name=Mask,json=mask,proto3" json:"Mask,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=X,json=x,proto3" json:"X,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=Y,json=y,proto3" json:"Y,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointerEvent) Reset()         { *m = PointerEvent{} }
func (m *PointerEvent) String() string { return proto.CompactTextString(m) }
func (*PointerEvent) ProtoMessage()    {}
func (*PointerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *PointerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointerEvent.Unmarshal(m, b)
}
func (m *PointerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointerEvent.Marshal(b, m, deterministic)
}
func (m *PointerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointerEvent.Merge(m, src)
}
func (m *PointerEvent) XXX_Size() int {
	return xxx_messageInfo_PointerEvent.Size(m)
}
func (m *PointerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PointerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PointerEvent proto.InternalMessageInfo

func (m *PointerEvent) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *PointerEvent) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PointerEvent) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointerEvent) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type KeyEvent struct {
	Down                 uint32   `protobuf:"varint,1,opt,name=Down,json=down,proto3" json:"Down,omitempty"`
	Key                  uint32   `protobuf:"varint,2,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyEvent) Reset()         { *m = KeyEvent{} }
func (m *KeyEvent) String() string { return proto.CompactTextString(m) }
func (*KeyEvent) ProtoMessage()    {}
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *KeyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyEvent.Unmarshal(m, b)
}
func (m *KeyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyEvent.Marshal(b, m, deterministic)
}
func (m *KeyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyEvent.Merge(m, src)
}
func (m *KeyEvent) XXX_Size() int {
	return xxx_messageInfo_KeyEvent.Size(m)
}
func (m *KeyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KeyEvent proto.InternalMessageInfo

func (m *KeyEvent) GetDown() uint32 {
	if m != nil {
		return m.Down
	}
	return 0
}

func (m *KeyEvent) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KeyEvent) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FbsSegment struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Timestamp            uint32   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FbsSegment) Reset()         { *m = FbsSegment{} }
func (m *FbsSegment) String() string { return proto.CompactTextString(m) }
func (*FbsSegment) ProtoMessage()    {}
func (*FbsSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *FbsSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FbsSegment.Unmarshal(m, b)
}
func (m *FbsSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FbsSegment.Marshal(b, m, deterministic)
}
func (m *FbsSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FbsSegment.Merge(m, src)
}
func (m *FbsSegment) XXX_Size() int {
	return xxx_messageInfo_FbsSegment.Size(m)
}
func (m *FbsSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FbsSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FbsSegment proto.InternalMessageInfo

func (m *FbsSegment) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *FbsSegment) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PixelFormat struct {
	BPP                  uint32   `protobuf:"varint,1,opt,name=BPP,json=bPP,proto3" json:"BPP,omitempty"`
	Depth                uint32   `protobuf:"varint,2,opt,name=Depth,json=depth,proto3" json:"Depth,omitempty"`
	BigEndian            uint32   `protobuf:"varint,3,opt,name=BigEndian,json=bigEndian,proto3" json:"BigEndian,omitempty"`
	TrueColor            uint32   `protobuf:"varint,4,opt,name=TrueColor,json=trueColor,proto3" json:"TrueColor,omitempty"`
	RedMax               uint32   `protobuf:"varint,5,opt,name=RedMax,json=redMax,proto3" json:"RedMax,omitempty"`
	GreenMax             uint32   `protobuf:"varint,6,opt,name=GreenMax,json=greenMax,proto3" json:"GreenMax,omitempty"`
	BlueMax              uint32   `protobuf:"varint,7,opt,name=BlueMax,json=blueMax,proto3" json:"BlueMax,omitempty"`
	RedShift             uint32   `protobuf:"varint,8,opt,name=RedShift,json=redShift,proto3" json:"RedShift,omitempty"`
	GreenShift           uint32   `protobuf:"varint,9,opt,name=GreenShift,json=greenShift,proto3" json:"GreenShift,omitempty"`
	BlueShift            uint32   `protobuf:"varint,10,opt,name=BlueShift,json=blueShift,proto3" json:"BlueShift,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixelFormat) Reset()         { *m = PixelFormat{} }
func (m *PixelFormat) String() string { return proto.CompactTextString(m) }
func (*PixelFormat) ProtoMessage()    {}
func (*PixelFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *PixelFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixelFormat.Unmarshal(m, b)
}
func (m *PixelFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixelFormat.Marshal(b, m, deterministic)
}
func (m *PixelFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixelFormat.Merge(m, src)
}
func (m *PixelFormat) XXX_Size() int {
	return xxx_messageInfo_PixelFormat.Size(m)
}
func (m *PixelFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_PixelFormat.DiscardUnknown(m)
}

var xxx_messageInfo_PixelFormat proto.InternalMessageInfo

func (m *PixelFormat) GetBPP() uint32 {
	if m != nil {
		return m.BPP
	}
	return 0
}

func (m *PixelFormat) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *PixelFormat) GetBigEndian() uint32 {
	if m != nil {
		return m.BigEndian
	}
	return 0
}

func (m *PixelFormat) GetTrueColor() uint32 {
	if m != nil {
		return m.TrueColor
	}
	return 0
}

func (m *PixelFormat) GetRedMax() uint32 {
	if m != nil {
		return m.RedMax
	}
	return 0
}

func (m *PixelFormat) GetGreenMax() uint32 {
	if m != nil {
		return m.GreenMax
	}
	return 0
}

func (m *PixelFormat) GetBlueMax() uint32 {
	if m != nil {
		return m.BlueMax
	}
	return 0
}

func (m *PixelFormat) GetRedShift() uint32 {
	if m != nil {
		return m.RedShift
	}
	return 0
}

func (m *PixelFormat) GetGreenShift() uint32 {
	if m != nil {
		return m.GreenShift
	}
	return 0
}

func (m *PixelFormat) GetBlueShift() uint32 {
	if m != nil {
		return m.BlueShift
	}
	return 0
}

type MessageType struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageType) Reset()         { *m = MessageType{} }
func (m *MessageType) String() string { return proto.CompactTextString(m) }
func (*MessageType) ProtoMessage()    {}
func (*MessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{5}
}

func (m *MessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageType.Unmarshal(m, b)
}
func (m *MessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageType.Marshal(b, m, deterministic)
}
func (m *MessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageType.Merge(m, src)
}
func (m *MessageType) XXX_Size() int {
	return xxx_messageInfo_MessageType.Size(m)
}
func (m *MessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageType.DiscardUnknown(m)
}

var xxx_messageInfo_MessageType proto.InternalMessageInfo

func (m *MessageType) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Rectangle struct {
	X                    uint32   `protobuf:"varint,1,opt,name=X,json=x,proto3" json:"X,omitempty"`
	Y                    uint32   `protobuf:"varint,2,opt,name=Y,json=y,proto3" json:"Y,omitempty"`
	Width                uint32   `protobuf:"varint,3,opt,name=Width,json=width,proto3" json:"Width,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=Height,json=height,proto3" json:"Height,omitempty"`
	Enc                  uint32   `protobuf:"varint,5,opt,name=Enc,json=enc,proto3" json:"Enc,omitempty"`
	Bytes                []byte   `protobuf:"bytes,6,opt,name=Bytes,json=bytes,proto3" json:"Bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{6}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Rectangle) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Rectangle) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Rectangle) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Rectangle) GetEnc() uint32 {
	if m != nil {
		return m.Enc
	}
	return 0
}

func (m *Rectangle) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type FramebufferUpdate struct {
	Rectangles           []*Rectangle `protobuf:"bytes,1,rep,name=rectangles,proto3" json:"rectangles,omitempty"`
	Timestamp            uint32       `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FramebufferUpdate) Reset()         { *m = FramebufferUpdate{} }
func (m *FramebufferUpdate) String() string { return proto.CompactTextString(m) }
func (*FramebufferUpdate) ProtoMessage()    {}
func (*FramebufferUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{7}
}

func (m *FramebufferUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FramebufferUpdate.Unmarshal(m, b)
}
func (m *FramebufferUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FramebufferUpdate.Marshal(b, m, deterministic)
}
func (m *FramebufferUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FramebufferUpdate.Merge(m, src)
}
func (m *FramebufferUpdate) XXX_Size() int {
	return xxx_messageInfo_FramebufferUpdate.Size(m)
}
func (m *FramebufferUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_FramebufferUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_FramebufferUpdate proto.InternalMessageInfo

func (m *FramebufferUpdate) GetRectangles() []*Rectangle {
	if m != nil {
		return m.Rectangles
	}
	return nil
}

func (m *FramebufferUpdate) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Demonstration struct {
	Initmsg              *InitMsg             `protobuf:"bytes,1,opt,name=initmsg,proto3" json:"initmsg,omitempty"`
	Fbupdates            []*FramebufferUpdate `protobuf:"bytes,2,rep,name=fbupdates,proto3" json:"fbupdates,omitempty"`
	Segments             []*FbsSegment        `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	Pointerevents        []*PointerEvent      `protobuf:"bytes,4,rep,name=pointerevents,proto3" json:"pointerevents,omitempty"`
	Keyevents            []*KeyEvent          `protobuf:"bytes,5,rep,name=keyevents,proto3" json:"keyevents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Demonstration) Reset()         { *m = Demonstration{} }
func (m *Demonstration) String() string { return proto.CompactTextString(m) }
func (*Demonstration) ProtoMessage()    {}
func (*Demonstration) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{8}
}

func (m *Demonstration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demonstration.Unmarshal(m, b)
}
func (m *Demonstration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demonstration.Marshal(b, m, deterministic)
}
func (m *Demonstration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demonstration.Merge(m, src)
}
func (m *Demonstration) XXX_Size() int {
	return xxx_messageInfo_Demonstration.Size(m)
}
func (m *Demonstration) XXX_DiscardUnknown() {
	xxx_messageInfo_Demonstration.DiscardUnknown(m)
}

var xxx_messageInfo_Demonstration proto.InternalMessageInfo

func (m *Demonstration) GetInitmsg() *InitMsg {
	if m != nil {
		return m.Initmsg
	}
	return nil
}

func (m *Demonstration) GetFbupdates() []*FramebufferUpdate {
	if m != nil {
		return m.Fbupdates
	}
	return nil
}

func (m *Demonstration) GetSegments() []*FbsSegment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *Demonstration) GetPointerevents() []*PointerEvent {
	if m != nil {
		return m.Pointerevents
	}
	return nil
}

func (m *Demonstration) GetKeyevents() []*KeyEvent {
	if m != nil {
		return m.Keyevents
	}
	return nil
}

func init() {
	proto.RegisterType((*InitMsg)(nil), "proto.InitMsg")
	proto.RegisterType((*PointerEvent)(nil), "proto.PointerEvent")
	proto.RegisterType((*KeyEvent)(nil), "proto.KeyEvent")
	proto.RegisterType((*FbsSegment)(nil), "proto.FbsSegment")
	proto.RegisterType((*PixelFormat)(nil), "proto.PixelFormat")
	proto.RegisterType((*MessageType)(nil), "proto.MessageType")
	proto.RegisterType((*Rectangle)(nil), "proto.Rectangle")
	proto.RegisterType((*FramebufferUpdate)(nil), "proto.FramebufferUpdate")
	proto.RegisterType((*Demonstration)(nil), "proto.Demonstration")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6b, 0xdb, 0x4a,
	0x10, 0x45, 0x96, 0xbf, 0x34, 0x8a, 0xef, 0x4d, 0xf6, 0x86, 0x20, 0x2e, 0x97, 0x8b, 0xeb, 0x27,
	0xbf, 0x24, 0x94, 0xb4, 0x14, 0xfa, 0x56, 0x5c, 0xc7, 0x4d, 0x09, 0x0e, 0x66, 0x9d, 0x7e, 0x41,
	0x5f, 0x24, 0x6b, 0x24, 0x0b, 0x5b, 0x2b, 0xb1, 0xbb, 0x4e, 0xe2, 0x87, 0xfe, 0x81, 0x42, 0x7f,
	0x40, 0xff, 0x6d, 0xd9, 0x0f, 0xc9, 0x76, 0xfa, 0xd0, 0x27, 0x7b, 0xe6, 0xec, 0x1c, 0xce, 0xcc,
	0x9c, 0x11, 0x40, 0x8c, 0x79, 0x71, 0x51, 0xf2, 0x42, 0x16, 0xa4, 0xa5, 0x7f, 0x06, 0x3f, 0x1a,
	0xd0, 0x79, 0xcf, 0x32, 0x39, 0x15, 0x29, 0xf9, 0x0f, 0x3c, 0x9a, 0x44, 0xd7, 0x18, 0xc6, 0xc8,
	0x03, 0xa7, 0xef, 0x0c, 0x3d, 0xea, 0xf1, 0x2a, 0x41, 0xfe, 0x07, 0xa0, 0x49, 0xf4, 0x11, 0xb9,
	0xc8, 0x0a, 0x16, 0x34, 0x34, 0x0c, 0xbc, 0xce, 0x90, 0x7f, 0xa1, 0x3b, 0x19, 0x5d, 0x63, 0x96,
	0x2e, 0x65, 0xe0, 0xf6, 0x9d, 0x61, 0x8f, 0x76, 0x13, 0x1b, 0x93, 0x00, 0x3a, 0x93, 0xd1, 0xa7,
	0x2c, 0x96, 0xcb, 0xa0, 0xa9, 0xa1, 0x4e, 0x62, 0x42, 0x85, 0xcc, 0x71, 0x71, 0xb7, 0x2d, 0x31,
	0x68, 0x19, 0x44, 0x98, 0x50, 0xa9, 0x99, 0xcb, 0x90, 0xcb, 0xbb, 0x2c, 0xc7, 0xa0, 0xad, 0x31,
	0x4f, 0x54, 0x09, 0xd2, 0x07, 0x7f, 0x8c, 0x62, 0x25, 0x8b, 0xf2, 0x36, 0xcc, 0x31, 0xe8, 0x68,
	0x39, 0x7e, 0xbc, 0x4b, 0x91, 0x97, 0xe0, 0xcf, 0xb2, 0x47, 0x5c, 0x4f, 0x0a, 0x9e, 0x87, 0x32,
	0xe8, 0xf6, 0x9d, 0xa1, 0x7f, 0x49, 0x4c, 0xf7, 0x17, 0x7b, 0x08, 0xf5, 0xcb, 0x5d, 0x30, 0xf8,
	0x0a, 0x47, 0xb3, 0x22, 0x63, 0x12, 0xf9, 0xd5, 0x3d, 0x32, 0x49, 0x08, 0x34, 0xa7, 0xa1, 0x58,
	0xe9, 0x71, 0xf4, 0x68, 0x33, 0x0f, 0xc5, 0x8a, 0x1c, 0x81, 0xf3, 0x59, 0x0f, 0xa0, 0x47, 0x9d,
	0x47, 0x15, 0x7d, 0xb1, 0x0d, 0x3b, 0x5b, 0xa5, 0x5a, 0x66, 0x39, 0x0a, 0x19, 0xe6, 0xa5, 0xed,
	0x75, 0x97, 0x18, 0xdc, 0x42, 0xf7, 0x06, 0xb7, 0x35, 0xf3, 0xb8, 0x78, 0x60, 0x15, 0x73, 0x5c,
	0x3c, 0x30, 0x72, 0x0c, 0xee, 0x0d, 0x6e, 0x2d, 0xb7, 0xbb, 0xc2, 0x27, 0x7c, 0xee, 0x53, 0xbe,
	0x37, 0x00, 0x93, 0x48, 0xcc, 0x31, 0xcd, 0x15, 0xe3, 0x29, 0xb4, 0xa2, 0xad, 0x44, 0xa1, 0x29,
	0x8f, 0xa8, 0x09, 0x0e, 0x19, 0x1a, 0x4f, 0x19, 0x7e, 0x36, 0x0e, 0xc6, 0xa4, 0x14, 0x8c, 0x66,
	0x33, 0x2b, 0xca, 0x8d, 0x66, 0x33, 0xc5, 0x3a, 0xc6, 0x52, 0x2e, 0x6d, 0x6d, 0x2b, 0x56, 0x81,
	0x62, 0x1d, 0x65, 0xe9, 0x15, 0x8b, 0xb3, 0x90, 0x55, 0xba, 0xa2, 0x2a, 0xa1, 0xd0, 0x3b, 0xbe,
	0xc1, 0xb7, 0xc5, 0xba, 0xe0, 0xf5, 0x14, 0xaa, 0x04, 0x39, 0x83, 0x36, 0xc5, 0x78, 0x1a, 0x3e,
	0xda, 0x95, 0xb7, 0xb9, 0x8e, 0x94, 0x83, 0xde, 0x71, 0x44, 0xa6, 0x10, 0xb3, 0xf0, 0x6e, 0x6a,
	0x63, 0xe5, 0x93, 0xd1, 0x7a, 0x83, 0x0a, 0xea, 0x18, 0x9f, 0x44, 0x26, 0x54, 0x55, 0x14, 0xe3,
	0xf9, 0x32, 0x4b, 0xcc, 0x92, 0x7b, 0xb4, 0xcb, 0x6d, 0xac, 0x3c, 0xab, 0x19, 0x0d, 0xea, 0x69,
	0x14, 0xd2, 0x3a, 0xa3, 0xbb, 0x58, 0x6f, 0xd0, 0xc0, 0x60, 0xbb, 0xa8, 0x12, 0x83, 0x67, 0xe0,
	0x4f, 0x51, 0x88, 0x30, 0x45, 0x6d, 0x48, 0x02, 0x4d, 0xa9, 0x7c, 0x6a, 0x17, 0xa6, 0xfe, 0x0f,
	0xbe, 0x81, 0x47, 0x71, 0x21, 0x43, 0x96, 0xae, 0xd1, 0xf8, 0xc2, 0x39, 0xf0, 0x45, 0xa3, 0xf2,
	0xc5, 0x29, 0xb4, 0x8c, 0xff, 0xcd, 0xac, 0x5a, 0x0f, 0xda, 0xfd, 0x67, 0xd0, 0xb6, 0x17, 0x63,
	0x86, 0xd4, 0x5e, 0x9a, 0x7b, 0x39, 0x06, 0xf7, 0x8a, 0x2d, 0xec, 0x78, 0x5c, 0x64, 0x0b, 0x55,
	0x3f, 0xd2, 0xbb, 0x6d, 0xef, 0xed, 0x76, 0xb0, 0x80, 0x93, 0x09, 0x0f, 0x73, 0x8c, 0x36, 0x49,
	0x82, 0xfc, 0x43, 0x19, 0x87, 0x12, 0xc9, 0x73, 0x00, 0x5e, 0x69, 0x52, 0x5e, 0x70, 0x87, 0xfe,
	0xe5, 0xb1, 0xf5, 0x7d, 0x2d, 0x96, 0xee, 0xbd, 0xf9, 0x83, 0x45, 0xbe, 0x37, 0xa0, 0x37, 0xc6,
	0xbc, 0x60, 0x42, 0xf2, 0x50, 0xaa, 0x53, 0x1f, 0x42, 0x27, 0x63, 0x99, 0xcc, 0x45, 0xaa, 0xdb,
	0xf5, 0x2f, 0xff, 0xb2, 0xf4, 0xf6, 0x4b, 0x42, 0x2b, 0x98, 0xbc, 0x02, 0x2f, 0x89, 0x36, 0x5a,
	0x97, 0x08, 0x1a, 0x5a, 0x4a, 0x60, 0xdf, 0xfe, 0x26, 0x9c, 0xee, 0x9e, 0x92, 0x73, 0xe8, 0x0a,
	0xe3, 0x6a, 0x11, 0xb8, 0xba, 0xec, 0xa4, 0x2a, 0xab, 0xfd, 0x4e, 0xeb, 0x27, 0xe4, 0x35, 0xf4,
	0x4a, 0x73, 0xb5, 0x78, 0xaf, 0x6b, 0x9a, 0xba, 0xe6, 0x9f, 0xea, 0xda, 0xf7, 0x2e, 0x9a, 0x1e,
	0xbe, 0x24, 0xe7, 0xe0, 0xad, 0x70, 0x6b, 0xcb, 0x5a, 0xba, 0xec, 0x6f, 0x5b, 0x56, 0x9d, 0x2a,
	0xdd, 0xbd, 0x88, 0xda, 0x1a, 0x7a, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x8a, 0x74, 0x30,
	0x4b, 0x05, 0x00, 0x00,
}
