// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitMsg struct {
	RfbHeader            string   `protobuf:"bytes,1,opt,name=RfbHeader,json=rfbHeader,proto3" json:"RfbHeader,omitempty"`
	RfbVersion           string   `protobuf:"bytes,2,opt,name=RfbVersion,json=rfbVersion,proto3" json:"RfbVersion,omitempty"`
	FBHeight             uint32   `protobuf:"varint,3,opt,name=FBHeight,json=fBHeight,proto3" json:"FBHeight,omitempty"`
	FBWidth              uint32   `protobuf:"varint,4,opt,name=FBWidth,json=fBWidth,proto3" json:"FBWidth,omitempty"`
	SecType              uint32   `protobuf:"varint,5,opt,name=SecType,json=secType,proto3" json:"SecType,omitempty"`
	StartTime            uint32   `protobuf:"varint,6,opt,name=StartTime,json=startTime,proto3" json:"StartTime,omitempty"`
	DesktopName          string   `protobuf:"bytes,7,opt,name=DesktopName,json=desktopName,proto3" json:"DesktopName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMsg) Reset()         { *m = InitMsg{} }
func (m *InitMsg) String() string { return proto.CompactTextString(m) }
func (*InitMsg) ProtoMessage()    {}
func (*InitMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *InitMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMsg.Unmarshal(m, b)
}
func (m *InitMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMsg.Marshal(b, m, deterministic)
}
func (m *InitMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMsg.Merge(m, src)
}
func (m *InitMsg) XXX_Size() int {
	return xxx_messageInfo_InitMsg.Size(m)
}
func (m *InitMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InitMsg proto.InternalMessageInfo

func (m *InitMsg) GetRfbHeader() string {
	if m != nil {
		return m.RfbHeader
	}
	return ""
}

func (m *InitMsg) GetRfbVersion() string {
	if m != nil {
		return m.RfbVersion
	}
	return ""
}

func (m *InitMsg) GetFBHeight() uint32 {
	if m != nil {
		return m.FBHeight
	}
	return 0
}

func (m *InitMsg) GetFBWidth() uint32 {
	if m != nil {
		return m.FBWidth
	}
	return 0
}

func (m *InitMsg) GetSecType() uint32 {
	if m != nil {
		return m.SecType
	}
	return 0
}

func (m *InitMsg) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *InitMsg) GetDesktopName() string {
	if m != nil {
		return m.DesktopName
	}
	return ""
}

type PointerEvent struct {
	Mask                 uint32   `protobuf:"varint,1,opt,name=Mask,json=mask,proto3" json:"Mask,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=X,json=x,proto3" json:"X,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=Y,json=y,proto3" json:"Y,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointerEvent) Reset()         { *m = PointerEvent{} }
func (m *PointerEvent) String() string { return proto.CompactTextString(m) }
func (*PointerEvent) ProtoMessage()    {}
func (*PointerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *PointerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointerEvent.Unmarshal(m, b)
}
func (m *PointerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointerEvent.Marshal(b, m, deterministic)
}
func (m *PointerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointerEvent.Merge(m, src)
}
func (m *PointerEvent) XXX_Size() int {
	return xxx_messageInfo_PointerEvent.Size(m)
}
func (m *PointerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PointerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PointerEvent proto.InternalMessageInfo

func (m *PointerEvent) GetMask() uint32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *PointerEvent) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PointerEvent) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PointerEvent) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type KeyEvent struct {
	Down                 uint32   `protobuf:"varint,1,opt,name=Down,json=down,proto3" json:"Down,omitempty"`
	Key                  uint32   `protobuf:"varint,2,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyEvent) Reset()         { *m = KeyEvent{} }
func (m *KeyEvent) String() string { return proto.CompactTextString(m) }
func (*KeyEvent) ProtoMessage()    {}
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *KeyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyEvent.Unmarshal(m, b)
}
func (m *KeyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyEvent.Marshal(b, m, deterministic)
}
func (m *KeyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyEvent.Merge(m, src)
}
func (m *KeyEvent) XXX_Size() int {
	return xxx_messageInfo_KeyEvent.Size(m)
}
func (m *KeyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KeyEvent proto.InternalMessageInfo

func (m *KeyEvent) GetDown() uint32 {
	if m != nil {
		return m.Down
	}
	return 0
}

func (m *KeyEvent) GetKey() uint32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *KeyEvent) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FbsSegment struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Timestamp            uint32   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FbsSegment) Reset()         { *m = FbsSegment{} }
func (m *FbsSegment) String() string { return proto.CompactTextString(m) }
func (*FbsSegment) ProtoMessage()    {}
func (*FbsSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *FbsSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FbsSegment.Unmarshal(m, b)
}
func (m *FbsSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FbsSegment.Marshal(b, m, deterministic)
}
func (m *FbsSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FbsSegment.Merge(m, src)
}
func (m *FbsSegment) XXX_Size() int {
	return xxx_messageInfo_FbsSegment.Size(m)
}
func (m *FbsSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FbsSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FbsSegment proto.InternalMessageInfo

func (m *FbsSegment) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *FbsSegment) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Demonstration struct {
	Initmsg              *InitMsg        `protobuf:"bytes,1,opt,name=initmsg,proto3" json:"initmsg,omitempty"`
	Segments             []*FbsSegment   `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	Pointerevents        []*PointerEvent `protobuf:"bytes,3,rep,name=pointerevents,proto3" json:"pointerevents,omitempty"`
	Keyevents            []*KeyEvent     `protobuf:"bytes,4,rep,name=keyevents,proto3" json:"keyevents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Demonstration) Reset()         { *m = Demonstration{} }
func (m *Demonstration) String() string { return proto.CompactTextString(m) }
func (*Demonstration) ProtoMessage()    {}
func (*Demonstration) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *Demonstration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demonstration.Unmarshal(m, b)
}
func (m *Demonstration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demonstration.Marshal(b, m, deterministic)
}
func (m *Demonstration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demonstration.Merge(m, src)
}
func (m *Demonstration) XXX_Size() int {
	return xxx_messageInfo_Demonstration.Size(m)
}
func (m *Demonstration) XXX_DiscardUnknown() {
	xxx_messageInfo_Demonstration.DiscardUnknown(m)
}

var xxx_messageInfo_Demonstration proto.InternalMessageInfo

func (m *Demonstration) GetInitmsg() *InitMsg {
	if m != nil {
		return m.Initmsg
	}
	return nil
}

func (m *Demonstration) GetSegments() []*FbsSegment {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *Demonstration) GetPointerevents() []*PointerEvent {
	if m != nil {
		return m.Pointerevents
	}
	return nil
}

func (m *Demonstration) GetKeyevents() []*KeyEvent {
	if m != nil {
		return m.Keyevents
	}
	return nil
}

func init() {
	proto.RegisterType((*InitMsg)(nil), "proto.InitMsg")
	proto.RegisterType((*PointerEvent)(nil), "proto.PointerEvent")
	proto.RegisterType((*KeyEvent)(nil), "proto.KeyEvent")
	proto.RegisterType((*FbsSegment)(nil), "proto.FbsSegment")
	proto.RegisterType((*Demonstration)(nil), "proto.Demonstration")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0x51, 0x9c, 0xac, 0xe3, 0x49, 0xdc, 0x3f, 0x6a, 0x0f, 0xa2, 0x94, 0x12, 0x72, 0xca,
	0x65, 0xf7, 0xb0, 0x3d, 0xf5, 0x56, 0x96, 0x34, 0x6c, 0x59, 0x76, 0x29, 0xca, 0xd2, 0x3f, 0xd0,
	0x8b, 0x5d, 0x8f, 0xbd, 0xc2, 0x48, 0x32, 0x92, 0xd8, 0xad, 0xbf, 0x66, 0x2f, 0xfd, 0x3a, 0xc5,
	0xb2, 0x1c, 0x37, 0x39, 0x99, 0x99, 0x37, 0xef, 0xe7, 0xa7, 0x19, 0x80, 0x02, 0xa5, 0xbe, 0x68,
	0x8c, 0x76, 0x9a, 0xce, 0xfc, 0x67, 0xfd, 0x97, 0x40, 0xfc, 0x59, 0x09, 0x77, 0x6b, 0x2b, 0xfa,
	0x16, 0x12, 0x5e, 0xe6, 0xd7, 0x98, 0x15, 0x68, 0x18, 0x59, 0x91, 0x4d, 0xc2, 0x13, 0x33, 0x34,
	0xe8, 0x3b, 0x00, 0x5e, 0xe6, 0x5f, 0xd1, 0x58, 0xa1, 0x15, 0x9b, 0x78, 0x19, 0xcc, 0xa1, 0x43,
	0xdf, 0xc0, 0x7c, 0x77, 0x75, 0x8d, 0xa2, 0x7a, 0x70, 0x2c, 0x5a, 0x91, 0x4d, 0xca, 0xe7, 0x65,
	0xa8, 0x29, 0x83, 0x78, 0x77, 0xf5, 0x4d, 0x14, 0xee, 0x81, 0x4d, 0xbd, 0x14, 0x97, 0x7d, 0xd9,
	0x29, 0x7b, 0xfc, 0x75, 0xdf, 0x36, 0xc8, 0x66, 0xbd, 0x62, 0xfb, 0xb2, 0x4b, 0xb3, 0x77, 0x99,
	0x71, 0xf7, 0x42, 0x22, 0x3b, 0xf3, 0x5a, 0x62, 0x87, 0x06, 0x5d, 0xc1, 0x62, 0x8b, 0xb6, 0x76,
	0xba, 0xb9, 0xcb, 0x24, 0xb2, 0xd8, 0xc7, 0x59, 0x14, 0x63, 0x6b, 0xfd, 0x13, 0x96, 0x5f, 0xb4,
	0x50, 0x0e, 0xcd, 0xa7, 0x47, 0x54, 0x8e, 0x52, 0x98, 0xde, 0x66, 0xb6, 0xf6, 0x0f, 0x4b, 0xf9,
	0x54, 0x66, 0xb6, 0xa6, 0x4b, 0x20, 0xdf, 0xfd, 0x53, 0x52, 0x4e, 0x7e, 0x77, 0xd5, 0x8f, 0x10,
	0x9d, 0xb4, 0xdd, 0xff, 0x9d, 0x90, 0x68, 0x5d, 0x26, 0x9b, 0x90, 0x7a, 0x6c, 0xac, 0xef, 0x60,
	0x7e, 0x83, 0xed, 0x81, 0xbc, 0xd5, 0x4f, 0x6a, 0x20, 0x17, 0xfa, 0x49, 0xd1, 0x17, 0x10, 0xdd,
	0x60, 0x1b, 0xd8, 0x51, 0x8d, 0x27, 0xbc, 0xe8, 0x94, 0xf7, 0x11, 0x60, 0x97, 0xdb, 0x3d, 0x56,
	0xb2, 0x23, 0xbe, 0x86, 0x59, 0xde, 0x3a, 0xb4, 0x1e, 0xb9, 0xe4, 0x7d, 0x71, 0x4c, 0x98, 0x9c,
	0x12, 0xfe, 0x10, 0x48, 0xb7, 0x28, 0xb5, 0xb2, 0xce, 0x64, 0xae, 0xbb, 0xc8, 0x06, 0x62, 0xa1,
	0x84, 0x93, 0xb6, 0xf2, 0x9c, 0xc5, 0xe5, 0xb3, 0xfe, 0xf6, 0x17, 0xe1, 0xe0, 0x7c, 0x90, 0xe9,
	0x39, 0xcc, 0x6d, 0xff, 0x6b, 0xcb, 0x26, 0xab, 0x68, 0xb3, 0xb8, 0x7c, 0x19, 0x46, 0xc7, 0x50,
	0xfc, 0x30, 0x42, 0x3f, 0x40, 0xda, 0xf4, 0xab, 0xc5, 0x47, 0xef, 0x89, 0xbc, 0xe7, 0x55, 0xf0,
	0xfc, 0xbf, 0x76, 0x7e, 0x3c, 0x49, 0xcf, 0x21, 0xa9, 0xb1, 0x0d, 0xb6, 0xa9, 0xb7, 0x3d, 0x0f,
	0xb6, 0x61, 0x9f, 0x7c, 0x9c, 0xc8, 0xcf, 0xbc, 0xf4, 0xfe, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0x99, 0xea, 0x8d, 0xba, 0x02, 0x00, 0x00,
}
