# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\ndemo.proto\x12\x05proto\"\xb5\x01\n\x07InitMsg\x12\x11\n\tRfbHeader\x18\x01 \x01(\t\x12\x12\n\nRfbVersion\x18\x02 \x01(\t\x12\x10\n\x08\x46\x42Height\x18\x03 \x01(\r\x12\x0f\n\x07\x46\x42Width\x18\x04 \x01(\r\x12\x0f\n\x07SecType\x18\x05 \x01(\r\x12\x11\n\tStartTime\x18\x06 \x01(\r\x12\x13\n\x0b\x44\x65sktopName\x18\x07 \x01(\t\x12\'\n\x0bPixelFormat\x18\x08 \x01(\x0b\x32\x12.proto.PixelFormat\"E\n\x0cPointerEvent\x12\x0c\n\x04Mask\x18\x01 \x01(\r\x12\t\n\x01X\x18\x02 \x01(\r\x12\t\n\x01Y\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\r\"8\n\x08KeyEvent\x12\x0c\n\x04\x44own\x18\x01 \x01(\r\x12\x0b\n\x03Key\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\r\".\n\nFbsSegment\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\r\"\xbb\x01\n\x0bPixelFormat\x12\x0b\n\x03\x42PP\x18\x01 \x01(\r\x12\r\n\x05\x44\x65pth\x18\x02 \x01(\r\x12\x11\n\tBigEndian\x18\x03 \x01(\r\x12\x11\n\tTrueColor\x18\x04 \x01(\r\x12\x0e\n\x06RedMax\x18\x05 \x01(\r\x12\x10\n\x08GreenMax\x18\x06 \x01(\r\x12\x0f\n\x07\x42lueMax\x18\x07 \x01(\r\x12\x10\n\x08RedShift\x18\x08 \x01(\r\x12\x12\n\nGreenShift\x18\t \x01(\r\x12\x11\n\tBlueShift\x18\n \x01(\r\"\\\n\tRectangle\x12\t\n\x01X\x18\x01 \x01(\r\x12\t\n\x01Y\x18\x02 \x01(\r\x12\r\n\x05Width\x18\x03 \x01(\r\x12\x0e\n\x06Height\x18\x04 \x01(\r\x12\x0b\n\x03\x45nc\x18\x05 \x01(\r\x12\r\n\x05\x42ytes\x18\x06 \x01(\x0c\"L\n\x11\x46ramebufferUpdate\x12$\n\nrectangles\x18\x01 \x03(\x0b\x32\x10.proto.Rectangle\x12\x11\n\ttimestamp\x18\x02 \x01(\r\"\xd2\x01\n\rDemonstration\x12\x1f\n\x07initmsg\x18\x01 \x01(\x0b\x32\x0e.proto.InitMsg\x12+\n\tfbupdates\x18\x02 \x03(\x0b\x32\x18.proto.FramebufferUpdate\x12#\n\x08segments\x18\x03 \x03(\x0b\x32\x11.proto.FbsSegment\x12*\n\rpointerevents\x18\x04 \x03(\x0b\x32\x13.proto.PointerEvent\x12\"\n\tkeyevents\x18\x05 \x03(\x0b\x32\x0f.proto.KeyEventb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INITMSG = _descriptor.Descriptor(
  name='InitMsg',
  full_name='proto.InitMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RfbHeader', full_name='proto.InitMsg.RfbHeader', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RfbVersion', full_name='proto.InitMsg.RfbVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FBHeight', full_name='proto.InitMsg.FBHeight', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FBWidth', full_name='proto.InitMsg.FBWidth', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecType', full_name='proto.InitMsg.SecType', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='proto.InitMsg.StartTime', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DesktopName', full_name='proto.InitMsg.DesktopName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PixelFormat', full_name='proto.InitMsg.PixelFormat', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=203,
)


_POINTEREVENT = _descriptor.Descriptor(
  name='PointerEvent',
  full_name='proto.PointerEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Mask', full_name='proto.PointerEvent.Mask', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='X', full_name='proto.PointerEvent.X', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='proto.PointerEvent.Y', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.PointerEvent.timestamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=274,
)


_KEYEVENT = _descriptor.Descriptor(
  name='KeyEvent',
  full_name='proto.KeyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Down', full_name='proto.KeyEvent.Down', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Key', full_name='proto.KeyEvent.Key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.KeyEvent.timestamp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=332,
)


_FBSSEGMENT = _descriptor.Descriptor(
  name='FbsSegment',
  full_name='proto.FbsSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='proto.FbsSegment.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.FbsSegment.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=380,
)


_PIXELFORMAT = _descriptor.Descriptor(
  name='PixelFormat',
  full_name='proto.PixelFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BPP', full_name='proto.PixelFormat.BPP', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Depth', full_name='proto.PixelFormat.Depth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BigEndian', full_name='proto.PixelFormat.BigEndian', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TrueColor', full_name='proto.PixelFormat.TrueColor', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RedMax', full_name='proto.PixelFormat.RedMax', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GreenMax', full_name='proto.PixelFormat.GreenMax', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BlueMax', full_name='proto.PixelFormat.BlueMax', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RedShift', full_name='proto.PixelFormat.RedShift', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GreenShift', full_name='proto.PixelFormat.GreenShift', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BlueShift', full_name='proto.PixelFormat.BlueShift', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=570,
)


_RECTANGLE = _descriptor.Descriptor(
  name='Rectangle',
  full_name='proto.Rectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='proto.Rectangle.X', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='proto.Rectangle.Y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Width', full_name='proto.Rectangle.Width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Height', full_name='proto.Rectangle.Height', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Enc', full_name='proto.Rectangle.Enc', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Bytes', full_name='proto.Rectangle.Bytes', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=664,
)


_FRAMEBUFFERUPDATE = _descriptor.Descriptor(
  name='FramebufferUpdate',
  full_name='proto.FramebufferUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rectangles', full_name='proto.FramebufferUpdate.rectangles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.FramebufferUpdate.timestamp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=666,
  serialized_end=742,
)


_DEMONSTRATION = _descriptor.Descriptor(
  name='Demonstration',
  full_name='proto.Demonstration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initmsg', full_name='proto.Demonstration.initmsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fbupdates', full_name='proto.Demonstration.fbupdates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segments', full_name='proto.Demonstration.segments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointerevents', full_name='proto.Demonstration.pointerevents', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyevents', full_name='proto.Demonstration.keyevents', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=955,
)

_INITMSG.fields_by_name['PixelFormat'].message_type = _PIXELFORMAT
_FRAMEBUFFERUPDATE.fields_by_name['rectangles'].message_type = _RECTANGLE
_DEMONSTRATION.fields_by_name['initmsg'].message_type = _INITMSG
_DEMONSTRATION.fields_by_name['fbupdates'].message_type = _FRAMEBUFFERUPDATE
_DEMONSTRATION.fields_by_name['segments'].message_type = _FBSSEGMENT
_DEMONSTRATION.fields_by_name['pointerevents'].message_type = _POINTEREVENT
_DEMONSTRATION.fields_by_name['keyevents'].message_type = _KEYEVENT
DESCRIPTOR.message_types_by_name['InitMsg'] = _INITMSG
DESCRIPTOR.message_types_by_name['PointerEvent'] = _POINTEREVENT
DESCRIPTOR.message_types_by_name['KeyEvent'] = _KEYEVENT
DESCRIPTOR.message_types_by_name['FbsSegment'] = _FBSSEGMENT
DESCRIPTOR.message_types_by_name['PixelFormat'] = _PIXELFORMAT
DESCRIPTOR.message_types_by_name['Rectangle'] = _RECTANGLE
DESCRIPTOR.message_types_by_name['FramebufferUpdate'] = _FRAMEBUFFERUPDATE
DESCRIPTOR.message_types_by_name['Demonstration'] = _DEMONSTRATION

InitMsg = _reflection.GeneratedProtocolMessageType('InitMsg', (_message.Message,), dict(
  DESCRIPTOR = _INITMSG,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.InitMsg)
  ))
_sym_db.RegisterMessage(InitMsg)

PointerEvent = _reflection.GeneratedProtocolMessageType('PointerEvent', (_message.Message,), dict(
  DESCRIPTOR = _POINTEREVENT,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.PointerEvent)
  ))
_sym_db.RegisterMessage(PointerEvent)

KeyEvent = _reflection.GeneratedProtocolMessageType('KeyEvent', (_message.Message,), dict(
  DESCRIPTOR = _KEYEVENT,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.KeyEvent)
  ))
_sym_db.RegisterMessage(KeyEvent)

FbsSegment = _reflection.GeneratedProtocolMessageType('FbsSegment', (_message.Message,), dict(
  DESCRIPTOR = _FBSSEGMENT,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.FbsSegment)
  ))
_sym_db.RegisterMessage(FbsSegment)

PixelFormat = _reflection.GeneratedProtocolMessageType('PixelFormat', (_message.Message,), dict(
  DESCRIPTOR = _PIXELFORMAT,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.PixelFormat)
  ))
_sym_db.RegisterMessage(PixelFormat)

Rectangle = _reflection.GeneratedProtocolMessageType('Rectangle', (_message.Message,), dict(
  DESCRIPTOR = _RECTANGLE,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.Rectangle)
  ))
_sym_db.RegisterMessage(Rectangle)

FramebufferUpdate = _reflection.GeneratedProtocolMessageType('FramebufferUpdate', (_message.Message,), dict(
  DESCRIPTOR = _FRAMEBUFFERUPDATE,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.FramebufferUpdate)
  ))
_sym_db.RegisterMessage(FramebufferUpdate)

Demonstration = _reflection.GeneratedProtocolMessageType('Demonstration', (_message.Message,), dict(
  DESCRIPTOR = _DEMONSTRATION,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:proto.Demonstration)
  ))
_sym_db.RegisterMessage(Demonstration)


# @@protoc_insertion_point(module_scope)
